openapi: 3.0.0
info:
  version: ''
  title: Abandoned Carts
tags:
  - name: Abandoned Carts
  - name: Abandoned Cart Settings
  - name: Abandoned Carts Settings
paths:
  /abandoned-carts/settings:
    get:
      summary: Get Global Abandoned Cart Settings
      description: Returns the global abandoned cart settings of a store.
      tags:
        - Abandoned
        - Carts
        - Global
        - Settings
    put:
      summary: Update Global Abandoned Cart Settings
      description: Updates the global abandoned cart settings of a store.
      tags:
        - Abandoned
        - Carts
        - Global
        - Settings
    parameters:
      - null
  /abandoned-carts/settings/channels/{channel_id}:
    get:
      summary: Get Channel Abandoned Cart Settings
      description: >-
        Returns the per-channel overrides for the abandoned cart settings of a
        store.
      tags:
        - Abandoned
        - Carts
        - Channels
        - Settings
    put:
      summary: Update Channel Abandoned Cart Settings
      description: >-
        Updates the per-channel overrides for the abandoned cart settings of a
        store.


        #### OAuth Scopes

        | UI Name                                      | Permission |
        Parameter                                     |

        |-||--|     

        | Information & Settings                       | modify     |
        `store_v2_information`                        |
      tags:
        - Abandoned
        - Carts
        - Channels
        - Settings
    parameters:
      - null
      - null
  /abandoned-carts/{token}:
    get:
      summary: 'Get An Abandoned Cart '
      description: >-
        This API retrieves the `cart_id` associated with the abandoned cart
        identified by the `{token}` parameter. To find the `{token}`, refer to
        the query string in the abandoned cart link provided in email
        notifications sent to shoppers.
      tags:
        - Abandoned
        - Carts
        - Tokens
    parameters:
      - null
      - null
