openapi: 3.0.3
info:
  title: Catalog - Product Variant Options
  version: ''
tags:
  - name: Product Variant Options
  - name: Values
paths:
  /catalog/products/{product_id}/options:
    get:
      tags:
        - Get
        - All
        - Product
        - Variant
        - Options
        - Catalog
        - Products
        - Product_id
        - Options
      summary: Get All Product Variant Options
      description: >-
        Returns a list of product *Variant Options*. Optional parameters can be
        passed in. 
    post:
      tags:
        - Create
        - Product
        - Variant
        - Option
        - Catalog
        - Products
        - Product_id
        - Options
      summary: Create a Product Variant Option
      description: >-
        Creates a *Variant Option*.


        **Required Fields**

        * display_name

        * type

        * option_values


        **Read-Only Fields**

        * id


        **Limits**

        * 255 characters option name length.


        **Notes**


        * Only one variant option at a time can be created; individual variant
        options will contain an array of multiple values.

        * There are several examples listed below that create options, but the
        SKUs are not updated and they are not a variant on the product. Variant
        SKUs must be created with a separate request.

        * Variant options will show on the storefront as an option that can be
        selected by the customer. A request like this could be used to add new
        choices to a variant that has already been created.

        * If more than one variant needs to be created, use the [Create a
        Product](/docs/rest-catalog/products#create-a-product) endpoint.
    parameters:
      - null
      - null
  /catalog/products/{product_id}/options/{option_id}:
    get:
      tags:
        - Get
        - Product
        - Variant
        - Option
        - Catalog
        - Products
        - Product_id
        - Options
        - Option_id
      summary: Get a Product Variant Option
      description: Returns a single *Variant Option*. Optional parameters can be passed in.
    put:
      tags:
        - Update
        - Product
        - Variant
        - Option
        - Catalog
        - Products
        - Product_id
        - Options
        - Option_id
      summary: Update a Product Variant Option
      description: |-
        Updates a *Variant Option*.

        **Read-Only Fields**
        * id
    delete:
      tags:
        - Delete
        - Product
        - Variant
        - Option
        - Catalog
        - Products
        - Product_id
        - Options
        - Option_id
      summary: Delete a Product Variant Option
      description: Deletes a *Variant Option*.
    parameters:
      - null
      - null
      - null
  /catalog/products/{product_id}/options/{option_id}/values:
    get:
      tags:
        - Get
        - All
        - Product
        - Variant
        - Option
        - Values
        - Catalog
        - Products
        - Product_id
        - Options
        - Option_id
        - Values
      summary: Get All Product Variant Option Values
      description: >-
        Returns a list of all *Variant Option Values*. Optional parameters can
        be passed in.
    post:
      tags:
        - Create
        - Product
        - Variant
        - Option
        - Value
        - Catalog
        - Products
        - Product_id
        - Options
        - Option_id
        - Values
      summary: Create a Product Variant Option Value
      description: |-
        Creates a *Variant Option Value*.

        **Required Fields**
        * label
        * sort_order

        **Read-Only Fields**
        * id

        **Limits**
        * 250 option values per option limit.
    parameters:
      - null
      - null
      - null
  /catalog/products/{product_id}/options/{option_id}/values/{value_id}:
    get:
      tags:
        - Get
        - Product
        - Variant
        - Option
        - Value
        - Catalog
        - Products
        - Product_id
        - Options
        - Option_id
        - Values
        - Value_id
      summary: Get a Product Variant Option Value
      description: >-
        Returns a single *Variant Option Value*. Optional parameters can be
        passed in.
    put:
      tags:
        - Update
        - Product
        - Variant
        - Option
        - Value
        - Catalog
        - Products
        - Product_id
        - Options
        - Option_id
        - Values
        - Value_id
      summary: Update a Product Variant Option Value
      description: |-
        Updates a *Variant Option Value*.

        **Read-Only Fields**
        * id
    delete:
      tags:
        - Delete
        - Product
        - Variant
        - Option
        - Value
        - Catalog
        - Products
        - Product_id
        - Options
        - Option_id
        - Values
        - Value_id
      summary: Delete a Product Variant Option Value
      description: Deletes a *Variant Option Value*.
    parameters:
      - null
      - null
      - null
      - null
