openapi: 3.0.1
info:
  title: Current Customer
  version: ''
tags:
  - name: Current Customers
paths:
  /customer/current.jwt:
    get:
      tags:
        - Get
        - Current
        - Customer
        - Customer
        - Current.jwt
      summary: Get Current Customer
      description: |-
        Identify logged-in customers securely via JavaScript.

        > #### Note
        > The Send a Test Request feature is not currently supported for th
