openapi: 3.0.3
info:
  title: Custom Template Associations
  version: ''
tags:
  - name: Custom Template Associations
paths:
  /storefront/custom-template-associations:
    parameters:
      - null
    get:
      summary: Get Custom Template Associations
      tags:
        - Get
        - Custom
        - Template
        - Associations
        - Storefront
        - Custom
        - Template
        - Associations
      description: >-
        Get a collection of the storeÊ¼s custom template associations across all
        storefronts
    put:
      summary: Upsert Custom Template Associations
      tags:
        - Upsert
        - Custom
        - Template
        - Associations
        - Storefront
        - Custom
        - Template
        - Associations
      description: >-
        Upsert new custom template associations data across all storefronts. If
        an existing record is found for the combination of channel ID, entity
        ID, and type, the existing record will be overwritten with the new
        template.
    delete:
      summary: Delete Custom Template Associations
      tags:
        - Delete
        - Custom
        - Template
        - Associations
        - Storefront
        - Custom
        - Template
        - Associations
      description: Delete custom template associations. At least one query parameter
