openapi: 3.0.3
info:
  title: Email Templates
tags:
  - name: Email Templates
paths:
  /marketing/email-templates:
    parameters:
      - null
    get:
      summary: Get Email Templates
      description: >-
        Get a list of email templates.


        > #### Note

        > The `/marketing/email-templates` endpoints only work after opting into
        the new email management experience from your storeʼs control panel. You
        can opt-in by visiting Email Templates. If you have already opted in,
        visiting the Email Templates page will return a `404` error, and you
        will be able to access the new Transactional Emails page.
      tags:
        - Get
        - Email
        - Templates
        - Marketing
        - Email
        - Templates
  /marketing/email-templates/{template-name}:
    parameters:
      - null
      - null
    get:
      summary: Get an Email Template
      description: >-
        Get a single global email template or a channel-specific email template
        override.


        > #### Note

        > The `/marketing/email-templates` endpoints only work after opting into
        the new email management experience from your storeʼs control panel. You
        can opt-in by visiting [Email
        Templates](https://login.bigcommerce.com/deep-links/manage/marketing/email-templates).
        If you have already opted in, visiting the [Email
        Templates](https://login.bigcommerce.com/deep-links/manage/marketing/email-templates)
        page will return a `404` error, and you will be able to access the new
        [Transactional
        Emails](https://login.bigcommerce.com/deep-links/manage/transactional-emails)
        page.
      tags:
        - Get
        - An
        - Email
        - Template
        - Marketing
        - Email
        - Templates
        - Template
        - Name
    put:
      summary: Update a Template
      description: >-
        Update a global template or create a channel-specific email template
        override.
      tags:
        - Update
        - Template
        - Marketing
        - Email
        - Templates
        - Template
        - Name
    delete:
      summary: Delete Email Template Override
      description: Removes a channel-specific email template override.
      tags:
        - Delete
        - Email
        - Template
        - Override
        - Marketing
        - Email
        - Templates
        - Template
        - Na
