openapi: 3.0.0
info:
  title: Geography
paths:
  /countries:
    get:
      description: >-
        Get a list of all countries available. A country or territory,
        identifiable by an ISO 3166 country code.
      summary: Get All Countries
      tags:
        - Get
        - All
        - Countries
        - Countries
  /countries/{id}:
    get:
      description: >-
        Returns a single *Country*.  Gets a country. A country or territory,
        identifiable by an ISO 3166 country code.
      summary: Get a Country
      tags:
        - Get
        - Country
        - Countries
        - Id
    parameters:
      - null
  /countries/{country_id}/states:
    get:
      description: |-
        Returns a list of *States* belonging to a *Country*. 
        A state or province, identifiable by an ISO 3166 subdivision code.
      summary: Get All Countryʼs States
      tags:
        - Get
        - All
        - Countryʼs
        - States
        - Countries
        - Id
        - Country_id
        - States
    parameters:
      - null
  /countries/{country_id}/states/{id}:
    get:
      description: |-
        Returns a *State*. 
        A state or province, identifiable by an ISO 3166 subdivision code.
      summary: Get a Countryʼs State
      tags:
        - Get
        - Countryʼs
        - State
        - Countries
        - Id
        - Country_id
        - States
    parameters:
      - null
      - null
  /countries/count:
    get:
      summary: Get a Count of All Countries
      tags:
        - Get
        - Count
        - Of
        - All
        - Countries
        - Countries
        - Id
        - Country_id
        - States
        - Count
      description: Returns a count of all countries.
  /countries/states/count:
    get:
      summary: Get a Count of All States
      tags:
        - Get
        - Count
        - Of
        - All
        - States
        - Countries
        - Id
        - Country_id
        - States
        - Count
      description: Returns a count of all states.
  /countries/states:
    get:
      summary: Get All States
      tags:
        - Get
        - All
        - States
        - Countries
        - Id
        - Country_id
        - States
        - Count
      description: Returns a list of all states.
  /countries/{country_id}/states/count:
    get:
      summary: Get a Count of Country’s States
      tags:
        - Get
        - Count
        - Of
        - Country’s
        - States
        - Countries
        - Id
        - Country_id
        - States
        - Count
      description: Returns a count of a countryʼs states.
    parameters:
      - null
tags:
  - name: Countries
  - name: nu
