openapi: 3.0.0
info:
  version: ''
  title: Payment Processing
tags:
  - name: Processing
paths:
  /payments:
    post:
      summary: Process Payments
      tags:
        - Process
        - Payments
        - Payments
      description: >-
        Process payments for an order. See [Payment
        Processing](/docs/store-operations/payments) for more 
