openapi: 3.0.1
info:
  title: Payment Methods (Deprecated)
  license:
    name: ''
  version: ''
tags:
  - name: Methods (Deprecated)
paths:
  /payments/methods:
    parameters:
      - null
    get:
      tags:
        - Get
        - All
        - Payment
        - Methods
        - Payments
        - Methods
      summary: Get All Payment Methods
      description: >
        Gets the list of enabled payment methods. Default sorting is by payment
        method, alphabetically from A to Z.


        > #### Note

        > Avoid using this API operation if possible. It is not supported;
        therefore, all enabled providers may
