openapi: 3.0.1
info:
  title: Pricing
  version: ''
tags:
  - name: Products
paths:
  /pricing/products:
    post:
      tags:
        - Get
        - Prices
        - Batch)
        - Pricing
        - Products
      summary: Get Prices (Batch)
      description: >-
        Calculate batch pricing for products for a specific channel, currency,
        and customer group.


        **Limits**

        * Limit of 50 concurre
