openapi: 3.0.0
info:
  title: Scripts
  version: ''
  license:
    name: ''
tags:
  - name: Scripts
paths:
  /content/scripts:
    parameters:
      - null
    post:
      summary: Create a Script
      tags:
        - Create
        - Script
        - Content
        - Scripts
      description: >-
        Creates a *Script*.


        **Required Fields**

        * name


        **Read Only Fields**

        * uuid


        **Limits**

        * 50 scripts per channel.


        **Notes**

        * If the `kind` is `src`:
          * Specify the `src` property. 
          * Optionally, you can supply a `load_method`. 
          * Do not specify the `html` field.
        * If the `kind` is `script_tag`:
          * Specify the `html` property.
          * Do not specify the `src` field.
        * Each app can have 10 scripts installed.

        * Multiple scripts can be created [per
        call](/docs/integrations/scripts#notes). 
    get:
      summary: Get All Scripts
      tags:
        - Get
        - All
        - Scripts
        - Content
        - Scripts
      description: >-
        Returns a list of *Scripts*. Optional parameters can be passed in.


        This operation will only return scripts generated by the API key and
        password used to create the script originally. 
  /content/scripts/{uuid}:
    parameters:
      - null
      - null
    get:
      summary: Get a Script
      tags:
        - Get
        - Script
        - Content
        - Scripts
        - Uuid
      description: Returns a single *Script*.
    put:
      summary: Update a Script
      tags:
        - Update
        - Script
        - Content
        - Scripts
        - Uuid
      description: Updates a *Script*.
    delete:
      summary: Delete a Script
      tags:
        - Delete
        - Script
        - Content
        - Scripts
        - Uuid
      description: Deletes
