openapi: 3.0.3
info:
  version: ''
  title: Shipping V3
tags:
  - name: Customs Information
paths:
  /shipping/products/customs-information:
    parameters:
      - null
    get:
      description: >-
        Get customs information for products.


        This list can be filtered to return customs information objects specific
        to a list of requested product_ids. This is achieved by appending the
        query string `?product_id:in=4,5,6` to the resource
        `/shipping/products/customs-information`.


        ```http

        GET /shipping/products/customs-information?product_id:in=4,5,6

        ```
      tags:
        - Get
        - Customs
        - Information
        - Shipping
        - Products
        - Customs
        - Information
      summary: Get Customs Information
    delete:
      summary: Delete Customs Information
      description: >-
        Deletes customs information objects for a product.


        ## Example


        This is a batch operation. The `product_id:in` query parameter is
        required.


        ```http

        DELETE /shipping/products/customs-information?product_id:in=4,5,6

        ```
      tags:
        - Delete
        - Customs
        - Information
        - Shipping
        - Products
        - Customs
        - Information
    put:
      summary: Upsert Customs Information
      description: >-
        Creates and updates product customs information.


        This is a batch operation where the creation of multiple customs
        information objects can be done with one `PUT` request.


        **Limits**

        * Limit of 50 customs information objects per `PUT` request.
      tags:
        - Upsert
        - Customs
        - Information
        - Shipping
        - Products
        - Customs
        - Informati
