openapi: 3.0.3
info:
  title: Sites
  version: ''
tags:
  - name: Sites
    description: >-
      Enables creation and management of external sites (domains) where shoppers
      shop. Allows for the correct shopping experience to be delivered and
      maintained (i.e. redirect URLs, email links) when a shopper goes through
      the purchasing process.
  - name: Site Routes
  - name: Site Certificate
paths:
  /sites:
    parameters:
      - null
    post:
      summary: Create a Site
      tags:
        - Create
        - Site
        - Sites
      description: >-
        Create a site that links a [headless
        storefront](/docs/storefront/headless) to a sales
        [channel](/docs/rest-management/channels).
    get:
      summary: Get Sites
      description: >-
        Get sites linked to a [headless storefront](/docs/storefront/headless)
        sales channels.
      tags:
        - Get
        - Sites
        - Sites
  /sites/{site_id}:
    get:
      summary: Get a Site
      tags:
        - Get
        - Site
        - Sites
        - Site_id
      description: Get a site with site ID `{site_id}`.
    put:
      summary: Update a Site
      tags:
        - Update
        - Site
        - Sites
        - Site_id
      description: Update a site with site ID `{site_id}`.
    delete:
      summary: Delete a Site
      tags:
        - Delete
        - Site
        - Sites
        - Site_id
      description: Delete a site with site ID `{site_id}`.
    parameters:
      - null
      - null
  /sites/{site_id}/routes:
    parameters:
      - null
      - null
    get:
      summary: Get a Site’s Routes
      tags:
        - Get
        - Site’s
        - Routes
        - Sites
        - Site_id
        - Routes
      description: Get a site’s routes.
    post:
      summary: Create a Site Route
      tags:
        - Create
        - Site
        - Route
        - Sites
        - Site_id
        - Routes
      description: >-
        Create routes that tell BigCommerce how to link to pages on a [headless
        storefront](/docs/storefront/headless).


        ## Usage Notes

        * For a list of supported route types, see [Route
        types](/docs/rest-management/sites#route-types).
    put:
      description: |-
        Upsert routes for site with ID `{site_id}`.

        ## Usage Notes
        * `id` is required when updating an existing route.
      summary: Update a Site’s Routes
      tags:
        - Update
        - Site’s
        - Routes
        - Sites
        - Site_id
        - Routes
  /sites/{site_id}/routes/{route_id}:
    get:
      summary: Get a Site Route
      tags:
        - Get
        - Site
        - Route
        - Sites
        - Site_id
        - Routes
        - Route_id
      description: Get a site’s route.
    put:
      summary: Update a Site Route
      tags:
        - Update
        - Site
        - Route
        - Sites
        - Site_id
        - Routes
        - Route_id
      description: |
        Update a site’s route.
    delete:
      summary: Delete a Site Route
      tags:
        - Delete
        - Site
        - Route
        - Sites
        - Site_id
        - Routes
        - Route_id
      description: Delete a site’s route.
    parameters:
      - null
      - null
      - null
  /sites/{site_id}/certificate:
    parameters:
      - null
      - null
    get:
      summary: Get a Site’s SSL/TLS Certificate Information
      description: Obtain information about a site’s SSL/TLS certificate.
      tags:
        - Get
        - Site’s
        - L/
        - Certificate
        - Information
        - Sites
        - Site_id
        - Routes
        - Route_id
        - Certificate
    put:
      summary: Upsert a Site’s SSL/TLS Certificate Information
      tags:
        - Upsert
        - Site’s
        - L/
        - Certificate
        - Information
        - Sites
        - Site_id
        - Routes
        - Route_id
        - Certificate
      description: >-
        - If a value for `url` is not supplied, the saved certificate is
        associated with the specified site’s `primary` URL.

        - Use caution. Because this endpoint upserts, supplying an SSL
        certificate for a domain that already has a certificate connected
        overwrites the domain’s extant certificate.'
  /sites/certificates:
    parameters:
      - null
    get:
      summary: Get Site Certificates
      tags:
        - Get
        - Site
        - Certificates
        - Sites
        - Site_id
        - Routes
        - Route_id
        - Certificate
        - Certificates
      description: Return all SSL certificates connected to domains wi
