openapi: 3.0.1
info:
  title: Storefront Orders
  version: ''
tags:
  - name: Order
paths:
  /orders/{orderId}:
    get:
      tags:
        - Get
        - Order
        - Id
      summary: Get Order
      description: >-
        Returns *Order* data. This will return order data immediately after an
        order is placed on the storefront.


        > #### Note

        > * Substitute your storefront domain for `yourstore.example.com`. 

        > * The Send a Test Request feature is not currently supported for th
