openapi: 3.0.1
info:
  title: Storefront Subscriptions
  version: ''
tags:
  - name: Subscription
paths:
  /subscriptions:
    post:
      tags:
        - Create
        - Subscription
        - Subscriptions
      summary: Create a Subscription
      description: >-
        Creates or updates an email subscription.


        By default, customers receive abandoned cart emails as soon as they
        provide their email address in the checkout flow. They can opt out using
        this endpoint.


        However, if **Store Settings > Miscellaneous > Require Consent** is
        enabled, Abandoned Cart Emails are not sent by default, and the customer
        should opt-in.


        > #### Note

        > * Substitute your storefront domain for `yourstore.example.com`. 

        > * The Send a Test Request feature is not currently supported for th
