openapi: 3.0.0
info:
  version: ''
  title: Store Information
tags:
  - name: Store Information
  - name: Time Zone
paths:
  /store:
    get:
      description: >-
        Returns metadata about the global settings for a store. Some of these
        values are independently configurable on a per-storefront or per-channel
        basis. For channel overrides, see [Store
        Settings](/docs/rest-management/settings).
      summary: Get Store Information
      tags:
        - Get
        - Store
        - Information
        - Store
  /time:
    get:
      description: >-
        Returns the system timestamp at the time of the request. The time
        resource is useful for validating API authentication details and testing
        client connections.
      summary: Get System Timestamp
      tags:
        - Get
        - System
        - Timestamp
        - Store
        - Ti
