openapi: 3.0.1
info:
  title: Storefront Customers
tags:
  - name: Customers
paths:
  /customers:
    post:
      tags:
        - Create
        - Customers
      description: >-
        Create a *Customer*.


        > #### Note

        > * Substitute your storefront domain for `yourstore.example.com`. 

        > * The Send a Test Request feature is not currently supported for this
        endpoint.
      summary: Crea
