openapi: 3.0.0
info:
  title: Store Logs V3 API
  version: ''
paths:
  /store/systemlogs:
    get:
      summary: Get System Logs
      description: 'Get system logs '
      tags:
        - Get
        - System
        - Logs
        - Store
        - Systemlogs
    parameters: []
tags:
  - name: nu
