openapi: 3.0.1
info:
  title: Storefront Form Fields (Beta)
  version: ''
tags:
  - name: Form Fields
paths:
  /form-fields:
    get:
      tags:
        - Get
        - Form
        - Fields
        - Form
        - Fields
      summary: Get Form Fields
      description: |-
        Gets form fields.

        > #### Note
        > * Substitute your storefront domain for `yourstore.example.com`. 
        > * The Send a Test Request feature is not currently supported for th
