openapi: 3.0.1
info:
  title: Tax Classes
  version: ''
tags:
  - name: Taxes
paths:
  /tax_classes:
    get:
      tags:
        - Get
        - All
        - Tax
        - Classes
        - Tax_classes
      summary: Get All Tax Classes
      description: |-
        Returns a list of all *Tax Classes* in a store.

        Default sorting is by tax-class id, from lowest to highest.
  /tax_classes/{id}:
    get:
      tags:
        - Get
        - Tax
        - Class
        - Tax_classes
        - Id
      summary: Get a Tax Class
      description: Returns a single
