openapi: 3.0.0
info:
  title: Tax Provider Connection
tags:
  - name: Tax Provider Connection
paths:
  /tax/providers/{provider_id}/connection:
    get:
      summary: Get Connection Status
      description: >
        Retrieve the connection status of the specified tax provider in the
        context of a store.


        > #### Note

        > * Requires **read** permissions on the **Information and Settings**
        scope.
      tags:
        - Get
        - Connection
        - Status
        - Tax
        - Providers
        - Provider_id
        - Connection
    delete:
      summary: Delete a Connection
      description: >
        Remove any previously set basic connection credentials for the specified
        provider. If the specified provider is the active tax provider on the
        store, the store's active tax provider will be reset to BigCommerce
        Manual Tax. It is suggested to call this endpoint during a single-click
        app [uninstall
        callback](/docs/integrations/apps/guide/callbacks#uninstall-callback).


        > #### Note

        > * This operation will be logged in [Store
        Logs](https://support.bigcommerce.com/s/article/Using-Store-Logs) under
        **Staff Actions**.

        > * Requires **write** permissions on the **Information and Settings**
        [scope](/docs/start/authentication/api-accounts#oauth-scopes).
      tags:
        - Delete
        - Connection
        - Tax
        - Providers
        - Provider_id
        - Connection
    put:
      description: >-
        Set authentication information associated with a merchant's account on
        the tax provider's infrastructure:

        - [HTTP Basic
        Authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)
        (developer.mozilla.org) credentials

        - (optional) Tax provider profile used in customized endpoint urls for
        tax provider calls. This is only available for tax providers that
        support this feature.


        The configured `username`, `password`, and `profile` (if available) is
        used to authenticate each API request to the Tax Provider from the
        associated store. 

        The tax provider's `profile` will be included in the url for [Tax
        Provider API](/docs/rest-contracts/tax) endpoints. 


        > #### Note

        > * This operation will be logged in [Store
        Logs](https://support.bigcommerce.com/s/article/Using-Store-Logs) under
        **Staff Actions**.

        > * Requires **write** permissions on the **Information and Settings**
        [scope](/docs/start/authentication/api-accounts#oauth-scopes).
      summary: Update a Connection
      tags:
        - Update
        - Connection
        - Tax
        - Providers
        - Provider_id
        - Connection
    parameters:
      - null
      - null
